# Generated by Django 2.2.4 on 2019-08-04 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=True, verbose_name='Publish')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('p_text', models.CharField(default='+', max_length=200, verbose_name='Positive choice text')),
                ('p_votes', models.IntegerField(default=0, verbose_name='Positive choice votes')),
                ('n_text', models.CharField(default='-', max_length=200, verbose_name='Negative choice text')),
                ('n_votes', models.IntegerField(default=0, verbose_name='Negative choice votes')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
