# Generated by Django 2.2.4 on 2019-08-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
