# Generated by Django 2.2.4 on 2019-08-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190828_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='avatar',
            new_name='slg',
        ),
    ]
