# Generated by Django 2.2.4 on 2019-08-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190828_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='polls.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slg',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
