# Generated by Django 2.2.4 on 2019-08-31 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190830_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2019, 8, 31, 14, 23, 37, 813249), max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
