# Generated by Django 2.2.4 on 2019-09-05 02:28

import datetime
from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190831_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='question',
            name='history',
            field=picklefield.fields.PickledObjectField(default=datetime.datetime(2019, 9, 5, 2, 28, 35, 39444), editable=False),
            preserve_default=False,
        ),
    ]
