# Generated by Django 2.2.4 on 2019-09-05 03:13

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190905_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='history',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
