# Generated by Django 2.2.4 on 2019-09-05 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190905_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='history',
        ),
        migrations.CreateModel(
            name='VoteHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('ip', models.CharField(max_length=50, verbose_name='voted ip')),
                ('choice', models.CharField(max_length=50, verbose_name='choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
