# Generated by Django 2.2.4 on 2019-09-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190905_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votehistory',
            name='user',
        ),
    ]
