# Generated by Django 2.2.4 on 2019-09-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_votehistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='votehistory',
            name='user',
            field=models.CharField(default='asd', max_length=150, verbose_name='username'),
            preserve_default=False,
        ),
    ]
